# Generated by Django 3.1.7 on 2021-03-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piquedgroup',
            name='interests',
            field=models.ManyToManyField(to='interests.Interest'),
        ),
        migrations.AddField(
            model_name='piqueduser',
            name='interests',
            field=models.ManyToManyField(to='interests.Interest'),
        ),
    ]
