# Generated by Django 3.1.7 on 2021-03-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piquedgroup',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='groups', to='interests.Interest'),
        ),
        migrations.AlterField(
            model_name='piqueduser',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='interests.Interest'),
        ),
    ]
