# Generated by Django 3.1.7 on 2021-03-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('user', '0002_auto_20210312_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='piqueduser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='info.Course'),
        ),
        migrations.AddField(
            model_name='piqueduser',
            name='program',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='info.program'),
        ),
    ]
