# Generated by Django 3.1.7 on 2021-03-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210312_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PiquedGroup',
        ),
    ]
