# Generated by Django 3.1.7 on 2021-03-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0004_delete_piquedgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='piqueduser',
            name='groups_created',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
