# Generated by Django 3.1.7 on 2021-03-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_piqueduser_groups_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piqueduser',
            name='groups_created',
        ),
    ]
