# Generated by Django 3.1.7 on 2021-03-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_piqueduser_groups_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='piqueduser',
            name='fcm_tokens',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
