# Generated by Django 3.1.7 on 2021-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_piqueduser_fcm_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piqueduser',
            name='fcm_tokens',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
