# Generated by Django 3.1.7 on 2021-04-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210407_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='piqueduser',
            name='shortcuts',
            field=models.CharField(blank=True, default='{"": ""}', max_length=2000),
        ),
    ]
