# Generated by Django 3.1.7 on 2021-04-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20210415_1316'),
        ('interests', '0001_initial'),
        ('user', '0008_auto_20210407_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.piquedgroup')),
                ('interest1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest1', to='interests.interest')),
                ('interest2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest2', to='interests.interest')),
                ('interest3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest3', to='interests.interest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.piqueduser')),
            ],
            options={
                'index_together': {('interest1', 'interest2', 'interest3')},
            },
        ),
    ]
