# Generated by Django 3.1.7 on 2021-04-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_piqueduser_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piqueduser',
            name='shortcuts',
            field=models.CharField(blank=True, default='{}', max_length=2000),
        ),
    ]
