# Generated by Django 3.1.7 on 2021-04-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_combos'),
        ('user', '0013_auto_20210420_1818'),
    ]

    operations = [
    ]
