# Generated by Django 3.1.7 on 2021-04-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
