# Generated by Django 3.1.7 on 2021-03-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210313_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='piquedgroup',
            name='creator',
            field=models.CharField(blank=True, max_length=150, verbose_name='Creator'),
        ),
    ]
