# Generated by Django 3.1.7 on 2021-03-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210317_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piquedgroup',
            name='created_by',
        ),
    ]
