# Generated by Django 3.1.7 on 2021-03-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_piqueduser_groups_created'),
        ('groups', '0005_remove_piquedgroup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='piquedgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to='user.piqueduser'),
        ),
    ]
