# Generated by Django 3.1.7 on 2021-04-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_piquedgroup_expired_at'),
        ('groups', '0007_piquedgroup_muted_users'),
    ]

    operations = [
    ]
