# Generated by Django 3.1.7 on 2021-04-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_merge_20210405_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piquedgroup',
            name='expired_at',
            field=models.DateField(null=True),
        ),
    ]
